#' @title Fetch PayPal Transactions with Recursive Bisection (Divide & Conquer)
#'
#' @description Extracts transaction details from the PayPal Reporting API.
#' Uses true recursion: if a timeframe exceeds the 10,000 items limit, it
#' dynamically cuts the timeframe in half over and over again until the chunks
#' are small enough for the API to process.
#'
#' @param token Character. The OAuth 2.0 Access Token generated by `get_paypal_token()`.
#' @param start_date Date or Character (YYYY-MM-DD). The start of the reporting window.
#' @param end_date Date or Character (YYYY-MM-DD). The end of the reporting window.
#' @param base_url Character. The PayPal API base URL. Defaults to the environment variable.
#'
#' @return A flattened `data.frame` containing all transaction details.
#' @export
#'
#' @importFrom httr RETRY add_headers status_code content
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr bind_rows
get_paypal_transactions <- function(token,
                                    start_date,
                                    end_date,
                                    base_url = Sys.getenv("PAYPAL_BASE_URL")) {
  if (missing(token)) stop("PayPal access token is missing.")

  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)
  if (start_date > end_date) stop("Startdatum darf nicht nach Enddatum liegen.")

  date_seq <- seq(start_date, end_date, by = "day")
  all_transactions <- list()

  # --- INTERNE HILFSFUNKTION 1: Der rohe API-Call ---
  fetch_window <- function(t_start, t_end) {
    current_page <- 1
    total_pages <- 1
    window_data <- list()

    while (current_page <= total_pages) {
      response <- httr::RETRY(
        verb = "GET", url = paste0(base_url, "/v1/reporting/transactions"),
        query = list(start_date = t_start, end_date = t_end, fields = "all", page_size = 100, page = current_page),
        httr::add_headers(Authorization = paste("Bearer", token)),
        times = 5, pause_base = 3, pause_cap = 60, terminate_on = c(400, 401, 403, 404)
      )

      status <- httr::status_code(response)
      res_text <- httr::content(response, as = "text", encoding = "UTF-8")

      # 400er Fehler abfangen und signalisieren
      if (status == 400 && grepl("RESULTSET_TOO_LARGE", res_text)) {
        return(list(status = "TOO_LARGE", data = NULL))
      } else if (status != 200) {
        stop(sprintf("API Error %s im Fenster %s: %s", status, t_start, res_text))
      }

      parsed <- jsonlite::fromJSON(res_text, flatten = TRUE)
      if (!is.null(parsed$transaction_details) && nrow(parsed$transaction_details) > 0) {
        window_data[[current_page]] <- parsed$transaction_details
      }
      total_pages <- ifelse(is.null(parsed$total_pages), 0, parsed$total_pages)
      current_page <- current_page + 1
    }

    if (length(window_data) > 0) {
      return(list(status = "SUCCESS", data = dplyr::bind_rows(window_data)))
    } else {
      return(list(status = "SUCCESS", data = data.frame()))
    }
  }

  # --- INTERNE HILFSFUNKTION 2: Die magische Rekursion ---
  fetch_recursive <- function(t_start_posix, t_end_posix, level = 1) {
    t_start_str <- format(t_start_posix, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
    t_end_str <- format(t_end_posix, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")

    indent <- paste0(rep("  ", level), collapse = "")
    if (level > 1) {
      message(sprintf("%s-> Pruefe Fenster: %s bis %s ...", indent, format(t_start_posix, "%H:%M:%S"), format(t_end_posix, "%H:%M:%S")))
    }

    # 1. Wir versuchen den Call
    res <- fetch_window(t_start_str, t_end_str)

    # 2. Wenn zu groß -> HALBIEREN UND NEU STARTEN
    if (res$status == "TOO_LARGE") {
      diff_secs <- as.numeric(difftime(t_end_posix, t_start_posix, units = "secs"))

      # Absolute Notbremse: Wenn das Fenster unter 60 Sekunden fällt (Extrem unwahrscheinlich)
      if (diff_secs < 60) {
        stop(sprintf("Mehr als 10.000 Transaktionen in unter 1 Minute (%s). Pammys hat das Internet gebrochen!", t_start_str))
      }

      message(sprintf("%s-> BOOM! Limit gesprengt. Halbiere Zeitfenster (%s Minuten)...", indent, round(diff_secs / 60, 1)))

      # Die exakte Mitte berechnen
      mid_point <- t_start_posix + floor(diff_secs / 2)

      Sys.sleep(1) # Kurze Atempause für die API

      # Rekursiver Aufruf für die linke und rechte Hälfte
      part1 <- fetch_recursive(t_start_posix, mid_point, level + 1)
      part2 <- fetch_recursive(mid_point + 1, t_end_posix, level + 1) # +1 Sekunde, um Überschneidungen zu vermeiden

      # Ergebnisse der Hälften zusammensetzen
      return(dplyr::bind_rows(part1, part2))
    } else {
      # 3. Wenn es klein genug war, einfach die Daten zurückgeben
      return(res$data)
    }
  }

  # --- HAUPTSCHLEIFE ÜBER JEDEN TAG ---
  message(sprintf("Starte rekursive Bisection-Extraktion fuer %s Tage...", length(date_seq)))

  for (i in seq_along(date_seq)) {
    current_date <- date_seq[i]

    # POSIXct Zeitstempel für Anfang und Ende des Tages
    t_start_posix <- as.POSIXct(paste0(current_date, " 00:00:00"), tz = "UTC")
    t_end_posix <- as.POSIXct(paste0(current_date, " 23:59:59"), tz = "UTC")

    message(sprintf("\n[%s/%s] Pruefe %s (Ganzer Tag)...", i, length(date_seq), current_date))

    # Wir übergeben den Tag an die Rekursions-Funktion
    day_data <- fetch_recursive(t_start_posix, t_end_posix, level = 1)

    if (!is.null(day_data) && nrow(day_data) > 0) {
      all_transactions[[as.character(current_date)]] <- day_data
    }

    Sys.sleep(1.5) # Pacing zwischen Tagen
  }

  if (length(all_transactions) == 0) {
    return(data.frame())
  }

  final_df <- dplyr::bind_rows(all_transactions)
  message(sprintf("\nExtraktion komplett! %s Transaktionen erfolgreich geladen.", nrow(final_df)))

  return(final_df)
}
