#' @title Fetch PayPal Transactions with Pagination and Rate Limiting
#'
#' @description Extracts transaction details from the PayPal Reporting API.
#' Handles pagination automatically and uses robust retry logic for API limits.
#' Note: PayPal restricts the date range to a maximum of 31 days per request.
#'
#' @param token Character. The OAuth 2.0 Access Token generated by `get_paypal_token()`.
#' @param start_date Date or POSIXct. The start of the reporting window.
#' @param end_date Date or POSIXct. The end of the reporting window.
#' @param base_url Character. The PayPal API base URL. Defaults to the environment variable.
#'
#' @return A flattened `data.frame` containing all transaction details.
#' @export
#'
#' @importFrom httr RETRY add_headers status_code content
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr bind_rows
#'
#' @examples \dontrun{
#' token <- get_paypal_token()
#' df_paypal <- get_paypal_transactions(
#'   token = token,
#'   start_date = Sys.Date() - 30,
#'   end_date = Sys.Date()
#' )
#' }
get_paypal_transactions <- function(token,
                                    start_date,
                                    end_date,
                                    base_url = Sys.getenv("PAYPAL_BASE_URL")) {
  if (missing(token)) {
    stop("PayPal access token is missing. Please provide a valid token.")
  }

  # Datums-Formatierung nach ISO-8601 (PayPal Standard)
  # Z.B. 2023-10-01T00:00:00Z
  start_str <- format(as.POSIXct(start_date), "%Y-%m-%dT00:00:00Z", tz = "UTC")
  end_str <- format(as.POSIXct(end_date), "%Y-%m-%dT23:59:59Z", tz = "UTC")

  transactions_list <- list()
  current_page <- 1
  total_pages <- 1 # Wird im ersten Durchlauf überschrieben

  message(sprintf("Starte PayPal Extraktion von %s bis %s...", start_str, end_str))

  while (current_page <= total_pages) {
    message(sprintf("Lade Seite %s von %s...", current_page, max(total_pages, current_page)))

    # Der robuste API-Call mit httr::RETRY
    response <- httr::RETRY(
      verb = "GET",
      url = paste0(base_url, "/v1/reporting/transactions"),
      query = list(
        start_date = start_str,
        end_date = end_str,
        fields = "all", # Holt alle verfügbaren Spalten (Käufername, Gebühren, etc.)
        page_size = 100,
        page = current_page
      ),
      httr::add_headers(Authorization = paste("Bearer", token)),
      times = 3, # Maximal 3 Versuche bei Fehler
      pause_base = 2, # 2 Sekunden warten
      pause_cap = 60, # Maximal 60 Sekunden warten
      terminate_on = c(400, 401, 403, 404) # Bei diesen Fehlern nicht neu versuchen
    )

    # Fehlerprüfung
    if (httr::status_code(response) != 200) {
      error_msg <- httr::content(response, as = "text", encoding = "UTF-8")
      stop(sprintf(
        "API Fehler auf Seite %s. Status: %s. Details: %s",
        current_page, httr::status_code(response), error_msg
      ))
    }

    # JSON parsen und flach klopfen
    json_text <- httr::content(response, as = "text", encoding = "UTF-8")
    parsed_data <- jsonlite::fromJSON(json_text, flatten = TRUE)

    # Transaktionen in die Liste speichern
    if (!is.null(parsed_data$transaction_details) && nrow(parsed_data$transaction_details) > 0) {
      transactions_list[[current_page]] <- parsed_data$transaction_details
    }

    # Pagination-Variablen aktualisieren
    total_pages <- parsed_data$total_pages
    current_page <- current_page + 1
  }

  # Liste von Dataframes zu einem einzigen Dataframe verbinden
  final_df <- dplyr::bind_rows(transactions_list)

  message(sprintf("Extraktion abgeschlossen: %s Transaktionen geladen.", nrow(final_df)))

  return(final_df)
}
